### ISSUE TITLE
splitticketbuyergui panics when importing decrediton config

### ISSUE THREAD

**Issue by alexlyp** [matheusd/dcr-split-ticket-matcher#2]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9a179a]

goroutine 1 [running]:
github.com/matheusd/dcr-split-ticket-matcher/pkg/buyer.InitConfigFromDecrediton(0xc4204537b0, 0xc, 0xc420485f30, 0x1)
        /home/user/git/src/github.com/matheusd/dcr-split-ticket-matcher/pkg/buyer/config-decrediton.go:228 +0x8ea
main.getDecreditonWalletName.func2()
        /home/user/git/src/github.com/matheusd/dcr-split-ticket-matcher/cmd/splitticketbuyergui/ui.go:62 +0x109
reflect.Value.call(0xa38100, 0xc420156f80, 0x13, 0xb7888a, 0x4, 0x1416ef0, 0x0, 0x0, 0xb675c0, 0xc42000c001, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xa38100, 0xc420156f80, 0x13, 0x1416ef0, 0x0, 0x0, 0x3, 0xc42004a070, 0xc42004a000)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/glib._go_glib_callback(0x34a0b80)
        /home/user/git/src/github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/glib/glib.go:814 +0x10f
github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/glib._cgoexpwrap_fe5c68f3714d__go_glib_callback(0x34a0b80)
        _cgo_gotypes.go:1832 +0x2b
github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
        _cgo_gotypes.go:11321 +0x41
github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/gtk.Main()
        /home/user/git/src/github.com/matheusd/dcr-split-ticket-matcher/vendor/github.com/mattn/go-gtk/gtk/gtk.go:307 +0x20
main.main()
        /home/user/git/src/github.com/matheusd/dcr-split-ticket-matcher/cmd/splitticketbuyergui/main.go:28 +0x1c3
```

**Comment by matheusd** [comment]
Ah, I had thought about this. You're running on your current decrediton master right? The advanced config was moved from the wallets into the global config, so that's probably why you're seeing this.

I'll fix to support the next decrediton version.
